#!/bin/sh
#
# @name Generic Hexarotor coaxial geometry
#
# @type Hexarotor Coaxial
# @class Copter
#
# @output MAIN1 front right top, CW; angle:60; direction:CW
# @output MAIN2 front right bottom, CCW; angle:60; direction:CCW
# @output MAIN3 back top, CW; angle:180; direction:CW
# @output MAIN4 back bottom, CCW; angle:180; direction:CCW
# @output MAIN5 front left top, CW; angle:-60; direction:CW
# @output MAIN6 front left bottom, CCW;angle:-60; direction:CCW
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default SYS_AUTOCONFIG 1

param set-default MAV_TYPE 13

param set-default MC_PITCHRATE_K 1.000
param set-default MC_PITCHRATE_I 0.30476
param set-default MC_PITCHRATE_D 0.00497

param set-default MC_ROLLRATE_K 1.000
param set-default MC_ROLLRATE_I 0.31657
param set-default MC_ROLLRATE_D 0.0058

param set-default MC_YAWRATE_K 1.000
param set-default MC_YAWRATE_I 0.18608

param set-default MC_PITCH_P 4.19108
param set-default MC_ROLL_P 4.06986
param set-default MC_YAW_P 4.87088

param set-default MPC_XY_VEL_P_ACC 5.0
param set-default MPC_XY_VEL_I_ACC 0.6
param set-default MPC_XY_VEL_D_ACC 0.25
param set-default MPC_Z_VEL_P_ACC 4.0
param set-default MPC_Z_VEL_I_ACC 2.0
param set-default MPC_Z_VEL_D_ACC 0.0

param set-default MPC_XY_P 2.0
param set-default MPC_Z_P 2.0

param set-default MPC_TILTMAX_AIR 20.0
param set-default MC_YAWRATE_MAX 60.0

param set-default BAT1_N_CELLS 6

param set-default IMU_GYRO_CUTOFF 40
param set-default IMU_DGYRO_CUTOFF 40

set MIXER hexa_cox

set PWM_OUT 123456
